version: 1
id: 'ysm'
name: 'Yokaiste’s Sandbox Mod'
description: 'An advanced WARNO sandbox overhaul'
enabled: true
priority: 0
allowWriteToModifiedFiles: true
variables:
  modTag: 'YSM'
  author: 'Yokaiste'
  modVersion: '2.4 [Open Beta]'
  alert:
    title: 'YSM Open Beta: read this now or suffer later'
    text: 'You are using the separate beta build.\nIt may contain bugs, weirdness, and other forms of high-grade sandbox nonsense.\n\nThis beta build will be removed when the beta ends, so stay subscribed to the stable YSM version as well if you want to keep playing afterward.\n\nYour feedback matters, so please visit the YSM Community and tell us what broke, what slapped, and what should be even more cursed.\n\nAlso yes, game updates love deleting decks, because apparently joy is overpowered.\n\nUseful links, like a civilized war criminal:\n - Stable YSM Workshop: t.ly/87TI3\n - YSM Community: t.ly/ZRnSO\n - Deck recovery & more: t.ly/Nk20O'
  links:
    - name: 'Stable version'
      url: 't.ly/87TI3'
    - name: 'YSM Community'
      url: 't.ly/ZRnSO'
    - name: 'Deck recovery & more'
      url: 't.ly/Nk20O'
  deckSlotCount: 80
  unlimitedPackUnitCount: 999
  unlimitedSupplyCapacity: '2000000.0'
  planeCap: 297
  excludeUnitsNotInAnyDivision: false
  commentDirectives:
    ignore: '${modTag}-ignore'
    everythingBelow: '${modTag}-ignore-everything-below'
    forceInclude: '${modTag}-force-include'
  gameplayConstants:
    defaultTimeLimitInMinutes: 41
    timeLimitTable:
      [
        5,
        10,
        15,
        21,
        25,
        30,
        35,
        41,
        45,
        50,
        55,
        60,
        67,
        80,
        89,
        101,
        110,
        120,
        150,
        180,
        210,
        240,
        300,
        360,
        404,
        480,
        540,
        600,
        666,
        720,
        1080,
        1337,
        2880,
        0,
      ]
    upkeepPercentValues:
      [
        0,
        0.25,
        0.5,
        0.75,
        1,
        1.25,
        1.5,
        1.75,
        2,
        2.25,
        2.5,
        2.75,
        3,
        3.5,
        4,
        4.5,
        5,
        5.5,
        6,
        6.5,
        7,
        7.5,
        8,
        8.5,
        9,
        9.5,
        10,
        15,
        20,
        30,
        40,
        50,
        99,
      ]
    scoreValues:
      [
        67,
        100,
        404,
        500,
        666,
        1000,
        1337,
        1500,
        1750,
        2000,
        2500,
        3000,
        3500,
        4000,
        4500,
        5000,
        5500,
        6000,
        6500,
        7000,
        7500,
        8008,
        8500,
        9001,
        9500,
        10000,
        12345,
        15000,
        17500,
        20000,
        25000,
        30000,
        35000,
        40000,
        42069,
        45000,
        50000,
        55000,
        60000,
        65000,
        70000,
        75000,
        80085,
        90000,
        95000,
        100000,
        200000,
        300000,
        400000,
        500000,
        694200,
        1000000,
        2000000,
      ]
    economyModeTokens:
      - "'CONQ_NONE'"
      - "'${modTag}_CON_0l'"
      - "'${modTag}_CON_0m'"
      - "'${modTag}_CON_0h'"
      - "'${modTag}_CON_1'"
      - "'${modTag}_CON_1l'"
      - "'${modTag}_CON_1m'"
      - "'${modTag}_CON_1h'"
      - "'${modTag}_CON_2'"
      - "'${modTag}_CON_2l'"
      - "'${modTag}_CON_2m'"
      - "'${modTag}_CON_2h'"
      - "'${modTag}_CON_3'"
      - "'${modTag}_CON_3m'"
      - "'${modTag}_CON_4'"
      - "'${modTag}_CON_4m'"
      - "'${modTag}_CON_5'"
      - "'${modTag}_CON_5m'"
      - "'${modTag}_CON_6'"
      - "'${modTag}_CON_6m'"
      - "'${modTag}_CON_7'"
      - "'${modTag}_CON_7m'"
      - "'${modTag}_CON_8'"
      - "'${modTag}_CON_8m'"
      - "'${modTag}_CON_9'"
      - "'${modTag}_CON_9m'"
      - "'${modTag}_CON_10'"
      - "'${modTag}_CON_15'"
      - "'${modTag}_CON_20'"
      - "'${modTag}_CON_30'"
      - "'${modTag}_CON_40'"
      - "'${modTag}_CON_50'"
      - "'${modTag}_CON_99'"
